#!/bin/sh
TERRAFORM_CMD="docker run -i --rm \
			-v `pwd`:/root/terraform \
			-v $HOME/.ssh:/root/.ssh \
			-e GOOGLE_CREDENTIALS=/root/.ssh/deploy-techevent-drone.json \
			-w /root/terraform \
			hashicorp/terraform:0.11.8"

${TERRAFORM_CMD} $@
